name: Node.js Package
on:
  push:
    branches:
      - main
      - feature/develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: set Version Number
        run: sed -i "s/1.0.0/1.0.${{github.run_number}}/"  package.json
      - name: Install dependencies
        run: npm install
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}